services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    ports:
      - "${VAULTWARDEN_HTTP_PORT:-9445}:80"
    volumes:
      - ${VAULTWARDEN_DATA_DIR:-./bitwarden}:/data:rw
    environment:
      - WEBSOCKET_ENABLED=${VAULTWARDEN_WEBSOCKET_ENABLED:-false}
      - SIGNUPS_ALLOWED=${VAULTWARDEN_SIGNUPS_ALLOWED:-false}
      - DOMAIN=${VAULTWARDEN_DOMAIN:-https://vault.example.com}
    networks:
      - homelab

networks:
  homelab:
    driver: bridge
